### ISSUE TITLE
Crashes with All Of Fabric 3 modpack

### ISSUE THREAD

**Issue by MeltedLiquid** [user11681/xradiation#1]
[crash-2020-09-04_05.45.57-client.txt](https://github.com/user11681/xradiation/files/5174687/crash-2020-09-04_05.45.57-client.txt)

**Comment by user11681** [comment]
That seems to be caused by the "Discoveries" module of Astromine.

**Comment by user11681** [comment]
Never mind; I understand now that my mod is indeed the problem here.

**Comment by MeltedLiquid** [comment]
> Never mind; I understand now that my mod is indeed the problem here.

i would really love a fix 
and thank you for the reply so quickly

**Comment by user11681** [comment]
Here's an experimental version that appears to fix the issue: https://github.com/user11681/xradiation/releases/tag/0.0.2

**Comment by MeltedLiquid** [comment]
Thank you so much! It worked! 😄
